version: '3.10-slim'

services:
  web:
    build: .
    ports:
      - "8110:8110"
    environment:
      - STRIPE_SECRET_KEY=your_secret_key
      - STRIPE_PUBLIC_KEY=your_public_key
      - DOMAIN=http://localhost:8110
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django_stripe
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: